Add parsing for max and min length for response body
parvez3019/go-swagger3 pull request #34
Opened 2023-11-04 01:32 UTC by Arlet2

Usage of this decision:
```json
type Response struct {
	Message string      `json:"message" maxLength:"10" minLength:"5"`
}
```

What do you think about this implementation?

2023-11-04 05:39 UTC, parvez3019 commented
Hey @Arlet2 thanks for this PR, the implementation looks good to me.
Would be great if you could add this in the `integration test`, so that we can merge this PR

2023-11-04 19:58 UTC, Arlet2 commented
So, I add some another fields for schema objects, and add example as optional field for parameter comment. Also I update integrations tests and Readme

2023-11-05 18:21 UTC, parvez3019 commented on integration_test/test_data/spec/actual.json
> +                  "$ref": "#/components/schemas/github.com.parvez3019.go-swagger3.model.GetRestaurantsResponse"
In this file, the package name should not be appended on this schemas, can you check what change actual changed this? 
Because as per the test configuration this should not happen in this file.

2023-11-05 18:21 UTC, parvez3019 requested changes
Please take a look at the comment

2023-11-05 19:44 UTC, Arlet2 commented on integration_test/test_data/spec/actual.json
> +                  "$ref": "#/components/schemas/github.com.parvez3019.go-swagger3.model.GetRestaurantsResponse"
I'm sorry, I was running test with packages after test without it and commit changes with actual test with packages. If you run tests now everything will be OK. Expected json files have possible changes. 

Do you want to revert this changes for actual.json? I've seen that this file wouldn't update since adding extra query parameter. 

I think it is not problem if this file

2023-11-05 21:06 UTC, Arlet2 commented
@parvez3019 I answered for your comment. I'm waiting for your reply

2023-11-06 01:59 UTC, parvez3019 commented on integration_test/test_data/spec/actual.json
> +                  "$ref": "#/components/schemas/github.com.parvez3019.go-swagger3.model.GetRestaurantsResponse"
Yes you are right, this would not impact the test and should be added to .gitignore.

Can you add this file to gitignore? And remove it?

2023-11-06 12:34 UTC, Arlet2 commented on integration_test/test_data/spec/actual.json
> +                  "$ref": "#/components/schemas/github.com.parvez3019.go-swagger3.model.GetRestaurantsResponse"
Okey, I've done it

2023-11-06 12:45 UTC, Arlet2 commented
#33 #26

2023-11-06 17:45 UTC, parvez3019 approved these changes

2023-11-06 17:46 UTC, parvez3019 commented
@Arlet2 Thanks for the changes and your contributions 💯

2023-11-06 17:46 UTC, merged